version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    container_name: ecommerce-app-dev
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.nuxt
    stdin_open: true
    tty: true
